# Generated by Django 5.0.3 on 2024-03-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdvertiserName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=150)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ItemAdvertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advertiser')),
            ],
        ),
    ]
