# Generated by Django 5.0.3 on 2024-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='NumberProduct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
